apiVersion: v1
kind: Service
metadata:
  namespace: mr-do-openhab
  name: mr-do-openhab-mqtt
spec:
  selector:
    app: mr-do-openhab-mqtt
  type: LoadBalancer
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
      name: mqtt
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: mqtt-websockets
