apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: mr-do-openhab
  name: mr-do-openhab-pv-data
  labels:
    usage: mr-do-openhab-pv-data
spec:
  capacity:
    storage: 4Gi
  storageClassName: nfs
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  nfs:
    server: mr0.local
    path: "/srv/nfs4/homes/mr/openhab"
    readOnly: false
