apiVersion: v1
kind: Service
metadata:
  namespace: mr-do-openhab
  name: mr-do-openhab-service
spec:
  selector:
    app: mr-do-openhab
  type: LoadBalancer
  loadBalancerIP: 192.168.0.2
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: webinterface
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: https-webinterface
    - port: 5683
      targetPort: 5683
      protocol: TCP
      name: CoIoT-peer
    - port: 8086
      targetPort: 8086
      protocol: TCP
      name: influxdb
    - port: 9125
      targetPort: 9125
      name: xml-rpc
    - port: 9126
      targetPort: 9126
      protocol: TCP
      name: bin-rpc
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: mqttlogviewer
    - port: 1883
      targetPort: 1883
      protocol: TCP
      name: mqtt
