apiVersion: v1
kind: PersistentVolume
metadata:
  name: mr-pv-data
  labels:
    usage: mr-pv-data
spec:
  capacity:
    storage: 16Gi
#  storageClassName: mr-nfs
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  nfs:
    server: mr0.local
    path: "/srv/nfs4/homes/mr/openhab"
    readOnly: false
